const CharacterActionTypes = {
  FETCH_CHARACTER_DETAIL_START: 'FETCH_CHARACTER_DETAIL_START',
  FETCH_CHARACTER_DETAIL_SUCCESS: 'FETCH_CHARACTER_DETAIL_SUCCESS',
  FETCH_CHARACTER_DETAIL_FAILURE: 'FETCH_CHARACTER_DETAIL_FAILURE'
};

export default CharacterActionTypes;
